version: "3"
services:
  redis-leader:
    build: .
    command: redis-server --bind 0.0.0.0 --protected-mode no
    ports:
      - "6379:6379"

  redis-follower:
    build: .
    command: redis-server --bind 0.0.0.0 --protected-mode no --slaveof redis-leader 6379
    ports:
      - "6378:6379"
    depends_on:
        - redis-leader
