apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis-leader
  name: redis-leader
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-leader
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: redis-leader
    spec:
      containers:
      - args:
        - redis-server
        - --bind
        - 0.0.0.0
        - --protected-mode
        - no
        image: redis-leader
        imagePullPolicy: ""
        name: redis-leader
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
