apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: redis-follower
  name: redis-follower
spec:
  ports:
  - name: "6378"
    port: 6378
    targetPort: 6379
  selector:
    io.kompose.service: redis-follower
status:
  loadBalancer: {}
